using System.Text;
using SurrealDb.Net.Design.Cli;
using SurrealDb.Net.Design.Schema;

namespace SurrealDb.Net.Design.Generation;

internal static class CSharpContextGenerator
{
    public static GeneratedFile Generate(DatabaseSchema schema, ScaffoldOptions options)
    {
        var contextName = CSharpIdentifier.Escape(options.ContextName);
        var path = Path.Combine(options.OutputDirectory, $"{options.ContextName}.cs");

        var records = schema.Records
            .OrderBy(record => record.TableName, StringComparer.OrdinalIgnoreCase)
            .Select(record => new GeneratedQueryProperty(
                CSharpIdentifier.ForClassName(record.TableName),
                CSharpIdentifier.ForQueryPropertyName(record.TableName)))
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using SurrealDb.Net;");

        if (!string.Equals(options.ContextNamespace, options.ModelNamespace, StringComparison.Ordinal))
        {
            builder.AppendLine($"using {options.ModelNamespace};");
        }

        builder.AppendLine();
        builder.AppendLine($"namespace {options.ContextNamespace};");
        builder.AppendLine();
        builder.AppendLine($"public partial class {contextName}");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly ISurrealDbClient _surrealDbClient;");
        builder.AppendLine();
        builder.AppendLine($"    public {contextName}(ISurrealDbClient surrealDbClient)");
        builder.AppendLine("    {");
        builder.AppendLine("        _surrealDbClient = surrealDbClient;");
        builder.AppendLine("    }");

        foreach (var record in records)
        {
            var typeName = CSharpIdentifier.Escape(record.TypeName);
            var propertyName = CSharpIdentifier.Escape(record.PropertyName);

            builder.AppendLine();
            builder.AppendLine($"    public IQueryable<{typeName}> {propertyName} => _surrealDbClient.Select<{typeName}>();");
        }

        builder.AppendLine("}");
        return new GeneratedFile(path, builder.ToString());
    }

    private sealed record GeneratedQueryProperty(string TypeName, string PropertyName);
}
