using System.Text;
using SurrealDb.Net.Design.Cli;
using SurrealDb.Net.Design.Schema;

namespace SurrealDb.Net.Design.Generation;

internal static class CSharpModelGenerator
{
    public static IReadOnlyList<GeneratedFile> Generate(DatabaseSchema schema, ScaffoldOptions options)
    {
        var files = new List<GeneratedFile>();
        var recordTypeNames = schema.Records.ToDictionary(
            record => record.TableName,
            record => CSharpIdentifier.ForClassName(record.TableName),
            StringComparer.OrdinalIgnoreCase); 
        var typeMapper = new CSharpTypeMapper(recordTypeNames);

        foreach (var record in schema.Records)
        {
            var className = recordTypeNames[record.TableName];
            var path = Path.Combine(options.OutputDirectory, $"{className}.cs");
            files.Add(new GeneratedFile(path, GenerateRecord(record, className, typeMapper, options)));
        }

        return files;
    }

    private static string GenerateRecord(
        RecordSchema record,
        string className,
        CSharpTypeMapper typeMapper,
        ScaffoldOptions options)
    {
        var properties = record.Fields
            .OrderBy(field => field.Name, StringComparer.OrdinalIgnoreCase)
            .Select(field => new GeneratedProperty(
                field,
                CSharpIdentifier.ForPropertyName(field.Name),
                typeMapper.Map(field.Kind)))
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");

        if (properties.Any(property => property.Type.IsNullable))
        {
            builder.AppendLine("using Dahomey.Cbor.Attributes;");
        }

        if (!string.IsNullOrWhiteSpace(options.RecordNamespace))
        {
            builder.AppendLine($"using {options.RecordNamespace};");
        }

        builder.AppendLine();
        builder.AppendLine($"namespace {options.ModelNamespace};");
        builder.AppendLine();
        builder.AppendLine($"[Table(\"{CSharpIdentifier.EscapeStringLiteral(record.TableName)}\")]");
        builder.AppendLine($"public partial class {CSharpIdentifier.Escape(className)} : {options.RecordBaseType}");
        builder.AppendLine("{");

        foreach (var property in properties)
        {
            builder.AppendLine($"    [Column(\"{CSharpIdentifier.EscapeStringLiteral(property.Field.Name)}\")]");
            if (property.Type.IsNullable)
            {
                builder.AppendLine("    [CborIgnoreIfDefault]");
            }

            var initializer = property.Type.RequiresDefaultInitializer ? " = default!;" : string.Empty;
            builder.AppendLine($"    public {property.Type.Name} {CSharpIdentifier.Escape(property.Name)} {{ get; set; }}{initializer}");
            builder.AppendLine();
        }

        if (record.Fields.Count == 0)
        {
            builder.AppendLine("    // This table has no schema fields defined yet.");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private sealed record GeneratedProperty(FieldSchema Field, string Name, CSharpPropertyType Type);
}
